version: "3"

services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: nova_senha
            MYSQL_DATABASE: admin-back
        networks:
            - laravel
        ports:
            - "3307:3306"

    laravel-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        depends_on:
            - mysql
        networks:
            - laravel
        ports:
            - "8080:80"

networks:
    laravel:
        driver: bridge
